config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'

  get 'sessions/new'

  
  resources :microposts do
    resources :comments
  end
  
  get 'users/new'
  resources :users do 
    get 'edit/editPassword', :to => 'users#editPassword'
    get 'edit/editVerification', :to => 'users#editVerification'
    get 'edit/editAvatar', :to => 'users#editAvatar'
    get 'myprofile/myComments', :to => 'users#allUserComment'
    get 'myprofile/commentToMe', :to => 'users#commentToUser'
    get '/myPost', :to => 'users#myPost'

  end
  get'/login' , to:'sessions#new'
  post'/login', to:'sessions#create'
  delete'/logout',to:'sessions#destroy'
  get'/signup' , to:'users#new'
  get'/profile' , to:'users#show'
  get'/edit' , to:'users#edit'

  resources :password_resets, only: [:new,:create,:edit,:update]
 
  get 'edit/editPassword', :to => 'users#editPassword'


  get '/micropost', to: 'microposts#new'
  get '/topic', to: 'static_pages#topic'
  get '/search', to: 'static_pages#search'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
        @microposts = Micropost.all
        @users = User.all
        @recentUsers = User.where("last_active > ?", 30.days.ago).limit(12)
    end

    def topic
        @filterMicroposts = Micropost.where("topic LIKE ?","%"+ params[:name]+"%")
        @users = User.all
        @recentUsers = User.where("last_active > ?", 30.days.ago).limit(12)
        @microposts = Micropost.all
    end

    def search
        @param= params[:q]
        @parameter = params[:q].downcase 
        @filterMicroposts = Micropost.where("lower(title) LIKE ? or lower(content) LIKE ?","%"+@parameter+" %","%"+@parameter+" %")
        @users = User.all
        @recentUsers = User.where("last_active > ?", 30.days.ago).limit(12)
        @microposts = Micropost.all
    end
 end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_header.html.erb
 <div class="row">
 <div class="leftcolumn">
 <%=link_to "Recent Post", root_path, class: "button"%>
<%=link_to "Selected Post",topic_path(:name => ""), class: "button"%>

<%if logged_in?%>
<%=link_to "My Setting", edit_user_path(current_user), class: "button"%>
<%end%>

 <div class="rightcolumn">
 <%=link_to "New Post", new_micropost_path, class: "button"%>
 </div> 

<div class="rightcolumn">
<div class="input-group-btn"> 
<form class ="form-inline my-2 my-lg-0"action="/search">
<input class= "form-control mr-sm-2" name="q" type="text" placeholder="Search" aria-label="Search" action="/search">
 
<%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
</form> </div> </div>

app/views/static_pages/_rightbar.html.erb
<div class="card">
     <h3>Recent Members</h3>
     <% @recentUsers.each do |user|%>
      <p><%=link_to gravatar_for(user,size:50) , user%></p>
     <%end%>  
        </div>
   <div class="card"><br><br>
     <h3>Topic</h3>
     <%=link_to "A.I", topic_path(:name => "A.I"), class: "round_button"%>
     <%=link_to "Game", topic_path(:name=>  "Game"), class: "round_button"%>
     <%=link_to "Rmit", topic_path(:name => "Rmit"), class: "round_button"%>
     <%=link_to "V.R.", topic_path(:name => "V.R."), class: "round_button"%>
<br><br>
     <h3>Post</h3>
      <% @microposts.each do |micropost|%>
             <p><%=link_to micropost.title, micropost,micropost: micropost%>
             Views: <%=micropost.view %></p>
         <%end%>
 <br>
   <h3>Links</h3>
   <%=link_to "Rails", 'https://rubyonrails.org/', class: "round_button"%>
   <%=link_to "Rmit", 'https://www.rmit.edu.au/', class: "round_button"%>
   <%=link_to "Heroku", 'https://dashboard.heroku.com/apps/rad2020-s3781183-s3785099', class: "round_button"%>
   <%=link_to "GitHub", 'https://github.com/s3781183/RAD2020_s3781183_s3785099', class: "round_button"%>

 </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title) %><br><br>
 
<%=render 'header'%>

   <div class="card">
     <h5>Recent Post</h5>
       <% @microposts.each do |micropost|%>
       <ol class="microposts">
            <br>  <p> <%=link_to gravatar_for(micropost.user,size:55), micropost.user%> 
            <p> <h5><%=link_to micropost.title , micropost,micropost: micropost%></h5></p>
           <p>  <%=link_to micropost.user.email , micropost.user%> 
             <%=micropost.created_at %>
             <%=micropost.topic %> 
             Views: <%=micropost.view %>
             Comments: <%=micropost.comments.count %></p>
         <%end%></ol>
   </div>
 </div>
  <div class="rightcolumn">
 <%=render 'rightbar'%>

app/views/static_pages/search.html.erb
<% provide(:title) %><br><br>
 
<%=render 'header'%>
   <div class="card">
     
      <h5>Search Results for "<%=@param%>"</h5>
       <% @filterMicroposts.each do |micropost|%>
       <ol class="microposts">
            <br>  <p> <%=link_to gravatar_for(micropost.user,size:55), micropost.user%> 
            <p> <h5><%=link_to micropost.title , micropost,micropost: micropost%></h5></p>
           <p>  <%=link_to micropost.user.email , micropost.user%> 
             <%=micropost.created_at %>
             <%=micropost.topic %> 
             Views: <%=micropost.view %>
             Comments: <%=micropost.comments.count %></p>
         <%end%></ol>
      
   </div>
 </div>

 
 <div class="rightcolumn">
 <%=render 'rightbar'%>
 </div>

app/views/static_pages/topic.html.erb
<% provide(:title) %><br><br>
 
<%=render 'header'%>
   <div class="card">
      <h5>Selected Post</h5>
       <% @filterMicroposts.each do |micropost|%>
       <ol class="microposts">
            <br>  <p> <%=link_to gravatar_for(micropost.user,size:55), micropost.user%> 
            <p> <h5><%=link_to micropost.title , micropost,micropost: micropost%></h5></p>
           <p>  <%=link_to micropost.user.email , micropost.user%> 
             <%=micropost.created_at %>
             <%=micropost.topic %> 
              Views: <%=micropost.view %>
             Comments: <%=micropost.comments.count %></p>
         <%end%></ol>
      
   </div>
 </div>
 <div class="rightcolumn">
 <%=render 'rightbar'%>