config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'

  get 'sessions/new'

  
  resources :microposts do
    resources :comments
  end
  
  get 'users/new'
  resources :users do 
    get 'edit/editPassword', :to => 'users#editPassword'
    get 'edit/editVerification', :to => 'users#editVerification'
    get 'edit/editAvatar', :to => 'users#editAvatar'
    get 'myprofile/myComments', :to => 'users#allUserComment'
    get 'myprofile/commentToMe', :to => 'users#commentToUser'
    get '/myPost', :to => 'users#myPost'

  end
  get'/login' , to:'sessions#new'
  post'/login', to:'sessions#create'
  delete'/logout',to:'sessions#destroy'
  get'/signup' , to:'users#new'
  get'/profile' , to:'users#show'
  get'/edit' , to:'users#edit'

  resources :password_resets, only: [:new,:create,:edit,:update]
 
  get 'edit/editPassword', :to => 'users#editPassword'


  get '/micropost', to: 'microposts#new'
  get '/topic', to: 'static_pages#topic'
  get '/search', to: 'static_pages#search'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    has_many :comments
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    # validates :user_id,presence: true
    validates :content,presence:true,length: {maximum:140}
    TITLE_LIST = ["A.I","Game","Rmit","V.R."]

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
    @users= User.all

  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost.view += 1
    @recentUsers = User.where("last_active > ?", 30.days.ago).limit(12)
    @microposts = Micropost.all
    @micropost.save
  end



  # GET /microposts/new
  def new
    @micropost = Micropost.new
    # @user = User.find(params[:id]) 
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)
    @micropost.user = current_user
    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html {redirect_to user_myPost_path(@micropost.user), notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

   

    private
    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:title,:topic,:content, :user_id)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= form.label :topic %>
    <%= form.select(:topic, Micropost::TITLE_LIST) %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, placeholder: "Enter post title Here"%>
  </div>

  <div class="field">
    <%= form.text_area :content , :cols => 40, :rows => 30 ,placeholder: "Enter your post here" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%=micropost.id%>">
    <%=link_to gravatar_for(micropost.user,size:50), micropost.user%>
    <span class="user"><%=link_to micropost.user.email, micropost.user%></span>
   <p> <span class="topic">Title:<%=link_to micropost.title, micropost,micropost: micropost%></span>

     <span class="timestamp">
      Posted <%=time_ago_in_words(micropost.created_at)%> ago.
      <%= link_to 'Delete', micropost, method: :delete, data: { confirm: 'Are you sure?' } %>
  </span></p>
  </li>

app/views/microposts/edit.html.erb
<br><br><h1>Editing Post</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<h1>Posts</h1><br><br>

<table>
  <thead>
    <tr>
      <th>Content</th>
  
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.title%></td>
        <td><%= micropost.user.email %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<br><br><h1>Post</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<div class="leftcolumn">
<div class="col-md-9">
<p id="notice"><%= notice %></p>
<br><br>
    <p>
          <strong>Topic:</strong>
          <%= @micropost.topic%>
      </p>
    <p>
      <strong>Title:</strong>
      <%= @micropost.title%>
    </p>

    <p>
      <strong>Content:</strong>
      <%= @micropost.content%>
    </p>

    <p>
      <strong>User:</strong>
      <%= @micropost.user.email %>
    </p>

    <p>
      <strong>Comments:</strong>
        <%= @micropost.comments.count %> 
        <p><%=render @micropost.comments%> </p>
    </p>
    <p>
      <%if logged_in?%><br><br>
       <strong>Add a comment</strong>
      <%=render'comments/form'%>
 
    </p>
    <%if @micropost.user_id==current_user.id%><br><br>

    <%= link_to 'Edit', edit_micropost_path(@micropost) %> 
    <%= link_to 'Back', microposts_path %>
    <% end %>
        <% end %>
  </div>
  </div>
<br><br>
<div class="rightcolumn">
  <div class="col-md-19">
  <%=render 'static_pages/rightbar'%>
</div>
</div>