config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'

  get 'sessions/new'

  
  resources :microposts do
    resources :comments
  end
  
  get 'users/new'
  resources :users do 
    get 'edit/editPassword', :to => 'users#editPassword'
    get 'edit/editVerification', :to => 'users#editVerification'
    get 'edit/editAvatar', :to => 'users#editAvatar'
    get 'myprofile/myComments', :to => 'users#allUserComment'
    get 'myprofile/commentToMe', :to => 'users#commentToUser'
    get '/myPost', :to => 'users#myPost'

  end
  get'/login' , to:'sessions#new'
  post'/login', to:'sessions#create'
  delete'/logout',to:'sessions#destroy'
  get'/signup' , to:'users#new'
  get'/profile' , to:'users#show'
  get'/edit' , to:'users#edit'

  resources :password_resets, only: [:new,:create,:edit,:update]
 
  get 'edit/editPassword', :to => 'users#editPassword'


  get '/micropost', to: 'microposts#new'
  get '/topic', to: 'static_pages#topic'
  get '/search', to: 'static_pages#search'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <p style="text-align:center"> Ruchelle Balasuriya-s3781183 Si Long Leong-s3785099<p>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
<%=link_to"News", root_path,id:"logo"%>
<nav><ul class="nav navbar-nav navbar-right">
<li><%=link_to"Home", root_path%></li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown">News <b class="caret"></b></a>
    <ul class="dropdown-menu" role ="menu">
        <li><%=link_to "A.I", topic_path(:name => "A.I") %></li>
        <li><%=link_to "Game", topic_path(:name=>  "Game")%></li>
        <li><%=link_to "Rmit", topic_path(:name => "Rmit")%></li>
        <li><%=link_to "V.R.", topic_path(:name => "V.R.")%></li>

    </ul>
    </li>
<%if logged_in?%>

<%if current_user.name.nil?%>
<li><%=link_to "#{current_user.email}", current_user %></li>
<%else%>
<li><%=link_to "#{current_user.name}", current_user %></li>
<%end%>
        <%# <li><%= link_to gravatar_for(current_user), :size => 125,logout_path, method: :delete%></li> 
        <li><%=link_to gravatar_for(current_user, size: 40), logout_path,method: :delete,id:"gravatar"%></li>
<%else%>
<li><%=link_to "Log in", login_path%></li>
<%end%>
</ul>
</nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%>| RAD_Assignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
  <br><br>
  <div class="spacer">
  <%flash.each do|message_type,message|%>
    <%=content_tag(:div, message, class:"alert alert-#{message_type}")%>      
    <%end%>
    <%= yield %>
  </body>
  </div>
  <%= render 'layouts/footer' %>

</html>